### ISSUE TITLE
AttributeError: 'Oep4' object has no attribute 'set_contract_address'

### ISSUE THREAD

**Issue by kenneth** [ontio/ontology-python-sdk#241]
```
Traceback (most recent call last):
  File "get_name.py", line 8, in <module>
    oep4.set_contract_address(contract_address)
AttributeError: 'Oep4' object has no attribute 'set_contract_address'
```

**Comment by NashMiao** [comment]
> ```
> Traceback (most recent call last):
>   File "get_name.py", line 8, in <module>
>     oep4.set_contract_address(contract_address)
> AttributeError: 'Oep4' object has no attribute 'set_contract_address'
> ```

sorry, this interface has updated, you can use in the following way:

```python
contract_address = 'd7b6a47966770c1545bf74c16426b26c0a238b16'
oep4 = sdk.neo_vm.oep4()
oep4.hex_contract_address = contract_address
```
