### ISSUE TITLE
在使用sdk.neo_vm().send_transaction去调用合约的时候，令pre_exec=False，即非预执行，会报错

### ISSUE THREAD

**Issue by Zou-XueYan** [ontio/ontology-python-sdk#42]
1. **场景：**
在使用sdk.neo_vm().send_transaction去调用合约的时候，令pre_exec=False，即非预执行，会报错
信息为：
```
Traceback (most recent call last):
  File "/Users/zou/PycharmProjects/ont_test/ont_contrast/demo/cli/test_cli.py", line 30, in test_join
    client.join_game(1, 2)
  File "/Users/zou/PycharmProjects/ont_test/ont_contrast/demo/cli/demo_cli.py", line 87, in join_game
    txid = self.sdk.neo_vm().send_transaction(self.contract_addr, acc, acc, 2000000, 500, func_join, False)
  File "/Users/zou/PycharmProjects/ont_test/ontology/smart_contract/neo_vm.py", line 36, in send_transaction
    self.__sdk.sign_transaction(tx, acct)
  File "/Users/zou/PycharmProjects/ont_test/ontology/ont_sdk.py", line 60, in sign_transaction
    tx_hash = tx.hash256()
  File "/Users/zou/PycharmProjects/ont_test/ontology/core/transaction.py", line 51, in hash256
    tx_serial = self.serialize_unsigned()
  File "/Users/zou/PycharmProjects/ont_test/ontology/core/transaction.py", line 35, in serialize_unsigned
    writer.write_bytes(bytes(self.payer))
TypeError: string argument without an encoding
```

就是因为/ontology/core/transaction.py的类Transaction在34行
```writer.write_bytes(bytes(self.payer))```
`self.payer`是一个string，没有指定encoding=？，所以报错

在ontology/smart_contract/neo_vm.py第34行，也就是在pre_exec=False的情况下，交易对象的创建：
```tx = Transaction(0, 0xd1, unix_time_now, gas_price, gas_limit, payer_acct.get_address_base58(), params, bytearray(), [], bytearray())```

`payer_acct.get_address_base58()`是string，而不是bytes，导致上面问题

**建议改成payer_acct.get_address_base58().encode()**

**Comment by wdx7266** [comment]
使用最新的SDK还会报错吗？

**Comment by Zou-XueYan** [comment]
我试一下

在2018年08月15日 19:01，wdx7266<notifications@github.com><mailto:notifications@github.com> 写道：

使用最新的SDK还会报错吗？

**Comment by lucas7788** [comment]
@Zou-XueYan   谢谢，我们已修复

**Comment by Zou-XueYan** [comment]
不客气啦～
